kde_config_dir: "{{ ansible_facts.env.HOME }}/.config"
kwin_scripts_dir: "{{ ansible_facts.env.HOME }}/.local/share/kwin/scripts"
kwin_config_dir: "{{ ansible_facts.env.HOME }}/.config/kwin"
user_scripts_dir: "{{ ansible_facts.env.HOME }}/.scripts"